logging:
  level: INFO
  loggers:
    com.github.deberth.todo: DEBUG

server:
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: secret
  url: jdbc:postgresql://192.168.99.100:5432/postgres
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    #hibernate.hbm2ddl.auto: update
  maxWaitForConnection: 5s
  validationQuery: "SELECT 1"